name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - 'src/**'
      - 'contrib/**'
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'contrib/**'
      - 'CMakeLists.txt'

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: curl -o cpplint.py https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py

      - name: Lint
        run: |
          python2 cpplint.py \
            --linelength=90 \
            --filter=-build/header_guard,-build/include,-build/c++11 \
            src/* \
            src/blueprints/* \
            src/core/* \
            src/objects/* \
            src/plugins/* \
            src/strategies/* \
            src/strategies/protoss/* \
            src/strategies/terran/* \
            src/strategies/zerg/*

  crossplatform_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel 2

  ladder_build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_FOR_LADDER=ON -DSC2_VERSION=4.10.0

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel 2
